name: Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (choose one)."
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Determine target
        id: target
        run: |
          env="${{ github.event.inputs.environment }}"
          echo "Chosen environment: $env"
          if [ -z "$env" ]; then
            echo "No environment provided. Use 'staging' or 'prod'."
            exit 1
          fi

          if [ "$env" = "prod" ]; then
            echo "target=prod" >> $GITHUB_OUTPUT
            echo "bucket=dam-prod.elanrif.com" >> $GITHUB_OUTPUT
          elif [ "$env" = "staging" ]; then
            echo "target=staging" >> $GITHUB_OUTPUT
            echo "bucket=dam-staging.elanrif.com" >> $GITHUB_OUTPUT
          else
            echo "Unsupported environment: $env"
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Sync to S3
        run: |
          echo "Deploying to ${{ steps.target.outputs.target }} -> s3://${{ steps.target.outputs.bucket }}"
          aws s3 sync . s3://${{ steps.target.outputs.bucket }} --delete --exclude "canalPlus/*" --exclude "uploads/*" --exclude ".git/*" --exclude ".github/*"
